from src.application.use_cases.google_search_use_case import GoogleSearchUseCase
from src.application.use_cases.add_to_favourites_use_case import AddToFavouritesUseCase
from src.application.use_cases.remove_from_favourites_use_case import RemoveFromFavouritesUseCase